# mode: "tray"（原本綁 tray 盤的狀態機） | "single"（單一訂單、不需要 tray 盤）
mode: tray
includes:
  classes: classes.yaml
  menus_mapping: menus_mapping.yaml
mqtt:
  host: localhost
  port: 1883
  base_topic: ocr
  session: v1
runtime:
  model:
    object_det: ./object_9cls_v01_00.dla
    ocr_det: ./yoshi_det_v01_01.dla
    ocr_cls: ./cls_v2.dla
    ocr_rec: ./yoshi_rec_v01_03.dla
    text: ./japan_dict.txt
  camera:
    source: 0
    width: 4024  # 4096 #4024
    height: 3036  # 3072 #3036
    device: 'hik' # hik | aravis
  stream:
    port: 9527
thresholds:
  ai_conf: 0.5
  ai_iou: 0.4
placement:
  roi_strink: 0.1
  iou_assign: 0.3
  iou_candidate: 0.8
  drift_iou_thresh: 0.95
stability:
  n_settle_frame: 6
  k_container_fail: 3
  k_container_new: 15
  tray_missing_frame: 15
  sticker_missing_frame: 15
camera_params:
    aravis:
        GainAuto: 'Off'
        Gain: 5.0
        ExposureAuto: 'Off'
        ExposureTime: 75000.0
        BalanceWhiteAuto: Continuous
    hik:
        DeviceLinkThroughputLimitPercentage: 
            value: 70
            type: 'int'
        AcquisitionFrameRateEnable:
            value: true
            type: 'bool'
        AcquisitionFrameRate: 
            value: 15.0
            type: 'float'
        ExposureMode:
            value: 'Timed'
            type: 'string'
        ExposureAuto:
            value: 'Off'
            type: 'string' 
            allowed:
                - 'Continuous'
                - 'Once'
                - 'Off'
        ExposureTime: 
            value: 75000.0
            type: 'float' 
            max: 500000
            min: 20
        GainAuto:
            value: 'Off'
            type: 'string' 
            allowed:
                - 'Continuous'
                - 'Once'
                - 'Off'
        Gain:
            value: 6.0
            type: 'float' 
            max: 23.981199264526367
            min: 0.0